services:
  - type: web
    name: cobalt-api
    env: node
    buildCommand: |
      cd api
      npm install -g pnpm
      pnpm install --no-frozen-lockfile
    startCommand: cd api/src && node cobalt.js
    envVars:
      - key: API_URL
        value: https://cobaltv1.onrender.com/
      - key: NODE_ENV
        value: production
    plan: starter
    healthCheckPath: / 